context:
  name: dooit-extras
  version: "0.2.0"

package:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
  url: https://pypi.org/packages/source/${{ name[0] }}/${{ name | replace("-", "_") }}/${{ name | replace("-", "_") }}-${{ version }}.tar.gz
  sha256: 4926e87ed9fca5fe47ea55ac5e6c959d32f7a590684772da6e9151ba42686e12

build:
  noarch: python
  script: python -m pip install . -vv
  number: 0

requirements:
  host:
    - python ${{ python_min }}.*
    - pip
    - poetry-core
  run:
    - python >=${{ python_min }}
    - dooit >=3.0.4,<4.0

tests:
  - python:
      imports:
      - dooit_extras
      pip_check: true
      python_version: ${{ python_min }}.*

about:
  homepage: https://github.com/dooit-org/dooit-extras
  summary: 'A collection of utilities to customize your'
  description: |
    Dooit extras is a library consisting of pre-built stuff for Dooit
    which includes various bar widgets and formatters, along with some
    pre-configured configs to get you started!
  license: MIT
  license_file: LICENSE
  documentation: https://dooit-org.github.io/dooit-extras/

extra:
  recipe-maintainers:
    - kraanzu
    - claudiushaag
